### ISSUE TITLE
Pass additional flags to commands?

### ISSUE THREAD

**Issue by djibi2** [saltstack-formulas/aptly-formula#24]
I want to use aptly to mirror a local unsigned repository.  To do this on the command line i would add the `-ignore-signatures=true` flag to the `aptly mirror create` command.  I didn't see that option in the pillar.example and wonder if there is a way to pass additional flags to the commands.

I am new to Salt, so I apologize if this is an obvious question.

**Comment by iggy** [comment]
There's not currently any functionality to do that. It looks like that code was contributed by @joe-bowman. Maybe you could sweet talk him into adding that functionality.

**Comment by gravyboat** [comment]
Since there's no option currently you could just fork the repo and modify either: https://github.com/saltstack-formulas/aptly-formula/blob/master/aptly/create_mirrors.sls#L12 or https://github.com/saltstack-formulas/aptly-formula/blob/master/aptly/create_mirrors.sls#L15 depending on whether you use a url or ppa to include your additional flag. Or we'd be happy to merge a PR to add that option with a default of `[]` like the other commands. It seems like @joe-bowman made it pretty easy to add additional options if we needed to.

**Comment by djibi2** [comment]
Thanks, I'll see what I can do.  I'm new to salt, but it seems like what I'm trying to add shouldn't require too much code.

**Comment by tedgar-everbridge** [comment]
re: create mirrors, the unless statement (aptly mirror show <name>) returns true, so the command is not executed - but returns false (not found) if run from the command line.  Any clue?

root@saltmin05:~# aptly mirror show ubuntu-trusty ; echo $?
ERROR: unable to show: mirror with name ubuntu-trusty not found
1

... (cut begging of salt apply output to node above)
          ID: add_40976EAF437D05B5_gpg_key
    Function: cmd.run
        Name: gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver keys.gnupg.net --recv-keys 40976EAF437D05B5
      Result: True
     Comment: Command "gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver keys.gnupg.net --recv-keys 40976EAF437D05B5" run
     Started: 14:50:27.047222
    Duration: 515.744 ms
     Changes:   
              ----------
              pid:
                  4545
              retcode:
                  0
              stderr:
                  gpg: requesting key 437D05B5 from hkp server keys.gnupg.net
                  gpg: key 437D05B5: "Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>" not changed
                  gpg: Total number processed: 1
                  gpg:              unchanged: 1
              stdout:
----------
          ID: add_3B4FE6ACC0B21F32_gpg_key
    Function: cmd.run
        Name: gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver keys.gnupg.net --recv-keys 3B4FE6ACC0B21F32
      Result: True
     Comment: Command "gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver keys.gnupg.net --recv-keys 3B4FE6ACC0B21F32" run
     Started: 14:50:27.563913
    Duration: 379.507 ms
     Changes:   
              ----------
              pid:
                  4568
              retcode:
                  0
              stderr:
                  gpg: requesting key C0B21F32 from hkp server keys.gnupg.net
                  gpg: key C0B21F32: "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>" not changed
                  gpg: Total number processed: 1
                  gpg:              unchanged: 1
              stdout:
----------
          ID: create_ubuntu-trusty_mirror
    Function: cmd.run
        Name: aptly mirror create -architectures='amd64' ubuntu-trusty http://us.archive.ubuntu.com/ubuntu/ trusty main
      Result: True
     Comment: unless execution succeeded
     Started: 14:50:27.945660
    Duration: 272.457 ms
     Changes:   

Summary for saltmin05.bur2.dev.ebcolo.com
-------------
Succeeded: 21 (changed=4)
Failed:     1
