### ISSUE TITLE
pillar.example gpg_passphrase quotes

### ISSUE THREAD

**Issue by tsmilam** [saltstack-formulas/aptly-formula#38]
gpg_passphrase needs outer double quotes so that salt will pass through the single quotes on the value. The state run will fail if the gpg_passphrase value contains spaces and is not quoted.

**Comment by aanriot** [comment]
Hello @tsmilam ,

Do you still have the issue?

**Comment by tsmilam** [comment]
I'm sorry, it's been so long that I don't recall and no longer use Salt (working at a new company now). I suppose this issue could be closed. Thanks!
