### ISSUE TITLE
[BUG] nginx.ng method doesn't exist anymore

### ISSUE THREAD

**Issue by djolitsu** [saltstack-formulas/aptly-formula#58]
In the  `nginx.sls` file, `nginx.ng.config` is included.
But there is a breaking change from the v1.0.0 of `nginx-formula`.
It would be necessary to change `nginx.ng.config` to `nginx.config`

**Comment by myii** [comment]
@djolitsu Good catch.  Would you be able to submit a PR with the fix?

**Comment by myii** [comment]
@djolitsu PR submitted: #59.
