### ISSUE TITLE
Trailing colon in bzip2 install is causing the formula to fail.

### ISSUE THREAD

**Issue by GregMSThompson** [saltstack-formulas/aptly-formula#9]
When running the formula I'm getting the following error message -

    Data failed to compile:
    ID 'bzip2' in SLS 'aptly' contains a short declaration (pkg.installed) with a trailing colon. When not passing any arguments to a state, the colon must be omitted.

**Comment by nmadhok** [comment]
Thanks @GregMSThompson

**Comment by GregMSThompson** [comment]
Your welcome! Thanks for fixing it so quickly :-)
